name: Build and Push to PH
on:
  push:
    branches: [main, production]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
#wip
